export const FINAL_RESULT = 'FINAL_RESULT' ;
export const CLICK_REMOVE_BUTTON = 'CLICK_REMOVE_BUTTON' ;
export const CLICK_INPUT_BUTTON = 'CLICK_INPUT_BUTTON' ;
export const CLICK_CLEAR_BUTTON = 'CLICK_CLEAR_BUTTON' ;
